import './globals.css'
import { Inter } from 'next/font/google'
import { RootProvider } from './app.providers'
import { AppContainer } from './components/AppContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <RootProvider>
        <body>
          <AppContainer>{children}</AppContainer>
        </body>
      </RootProvider>
    </html>
  )
}
